print("Hello.")
print("I am 11 years old.")
print("My name is gega.")
print("My last name is Dolidze.")
print("I like porgraming.")
print("I like legos.")
print("I like drawing.")
print("My best friend is Noah.")
print("I like snakes.")
print("I like axolotoles.")
print("I like making stuff with clay.")
print("I know how to speak and write english.")
print("I like to comunicate in english.")
print("I have blond hair.")
print("I have blue eyes.")
print("I wear glasses.")
print("I like the colors black red and purple.")
print("I was born in on the 21st of October in 2013.")
print("Thats 20 print codes!")
print("Bye!")